### ISSUE TITLE
some pullzed in header.p4

### ISSUE THREAD

**Issue by peiqiaoWang** [Emil-501/block.p4#3]
```
header_type tcp_t {
    fields {
        srcPort : 16;
        dstPort : 16;
        seqNo : 32;
        ackNo : 32;
        dataOffset : 4;
        res : 4;
        flags : 8;
        window : 16;
        checksum : 16;
        urgentPtr : 16;
    }
}
```

should be modify ```res : 4``` and ```flags : 8``` to  ```res : 6``` and  ```flags : 6```? reasonable?

According to the links 
http://blog.csdn.net/a19881029/article/details/29557837

**Comment by chenxiang2019** [comment]
One thing should be noticed that, the blogs in Chinese are not correctly all the time. The best way to get the network protocol informations is to refer to the RFC files or the wiki pedia.

You can refer the [Transmission Control Protocol](https://en.wikipedia.org/wiki/Transmission_Control_Protocol) here in wikipedia or the original RFC file here: [RFC 793 Page 14](https://tools.ietf.org/html/rfc793).

To be honest, because so many technologies have been present, there is no unified definition about this header format bettween different technologies, that means different technologies may use different field length to define the packet. 

So feel free to define this field length with your target.

**Comment by peiqiaoWang** [comment]
thank you for your help~
